config/routes.rb
Rails.application.routes.draw do

  resources :errors_logs, :only => [:create]
  resources :settings
  resources :users_banks, :except => [:edit, :show]
  resources :banks, :only => [:create]
  resources :selfie_verifications, :only => [:create, :update]
  resources :address_verifications, :only => [:create, :update]
  resources :nationalid_verifications, :only => [:create, :update]
  resources :user_infos, :only => [:create]
  namespace :api, defaults: {format: 'json'} do
    namespace :v1 do
      resources :users_banks
      resources :watchdogs
      resources :users
      resources :countries
      resources :affilate_programs
      resources :selfie_verifications, :except => [:index, :destroy]
      resources :address_verifications, :except => [:index, :destroy]
      resources :nationalid_verifications, :except => [:index, :destroy]
      resources :translations
      post "users/create" => "users#create"
      get "homepage" => "users#homepage"
      post "confirmmail" => "users#confirmmail"
      post "resend_confirmmail" => "users#resend_confirmmail"
      get "two_factor" => "users#get_two_factor"
      post "two_factor" => "users#post_two_factor"
      get "send_confirmation_email" => "users#send_confirmation_email"
      get "generate_qr_code" => "users#generate_qr_code"
      get "confirm_google_code" => "users#confirm_google_code"
      get "user_log" => "watchdogs#user_log"
      get "active_sessions" => "logins#active_sessions"
      post 'auth_user' => 'authentication#authenticate_user'
      post "unlockaccount" => "authentication#unlockaccount"
      post "send_invitation_email" => "affilate_programs#send_invitation_email"
      post 'getEditToken' => 'authentication#getEditToken'
      # resources :cards
      #get "buy_card" => "cards#buy_card" 
      # resources :cards_categories
      get "display_cards_categories" => "cards_categories#display_cards_categories"
      resources :addresses, :except => [:new, :edit, :show]
      post "update_address" => "addresses#update_address"
      get "user_addresses" => "addresses#user_addresses"
      resources :user_wallets
      get "transfer_balance" => "user_wallets#transfer_balance"
      post "transfer_balance" => "user_wallets#transfer_balancepost"
      get "send_sms" => "user_wallets#send_sms"
      post "send_sms_post" => "user_wallets#send_sms_post"
      post "verifysms_post" => "user_wallets#verifysms_post"
      get "verifysms" => "user_wallets#verifysms" 
      get "user_wallet_balance" => "user_wallets#user_wallet_balance"
      resources :notifications
      resources :notifications_settings
      get "user_notifications" => "notifications#user_notifications"
      get "search_notifications" => "notifications#search"
      get "add_defualt_notifications" => "notifications_settings#add_defualt_notifications"
      resources :uploads
      resources :money_ops
      resources :ticket_departments
      resources :tickets, :except => [:new, :edit, :update]
      post 'tickets/reply' => 'tickets#create_reply'
      get "close_ticket" => "tickets#close_ticket"
      get "report_ticket" => "tickets#report_ticket"
      post "evaluate_ticket" => "tickets#evaluate_ticket"
      resources :payers_blogs
      get "users_blogs" => "payers_blogs#users_blogs"
      get "catblogs" => "payers_blogs#catblogs"
      get "display_blog" => "payers_blogs#display_blog"
      get "blogs_sitemap.xml" => "payers_blogs#sitemap", :format => "xml", :as => :sitemap
      get "payers_blogs_categories" => "payers_blogs#payers_blogs_categories"
      resources :settings
      get "mail_setting" => "settings#mail_setting"
      
    end
  end









  resources :affilate_programs, :only => [:create, :destroy]
  #resources :countries, :only => [:index, :show]
  resources :logins, :only => [:create, :destroy]
  resources :verifications, :only => [:create, :update, :destroy]
  resources :watchdogs, :only => [:create, :show, :destroy]
  resources :users, :except => [:index, :edit]
  # root "users#dashboard"
  root "users#homepage"
  get "confirmmail" => "users#confirmmail"
  get "unlockaccount" => "users#unlockaccount"
  get "two_factor" => "users#get_two_factor"
  post "two_factor" => "users#post_two_factor"
  get "resend_two_factor" => "users#resend_two_factor"
  get "dashboard" => "users#dashboard"
  get "destroy_all_sessions" => "clearance/sessions#destroy_all_sessions"
  get "destroy_one_session" => "clearance/sessions#destroy_one_session"
  
  match 'pass_to_security_settings', to: 'users#pass_to_security_settings', via: %i(get patch post)
  get "secure_my_account" => "users#secure_my_account"
  
  get "check_mail" => "users#check_mail"
  get "check_phone" => "users#check_phone"
  get "check_country_code" => "users#check_country_code"
  get "after_sign_up" => "users#after_sign_up"
  get "resend_confirmation_mail" => "users#resend_confirmation_mail"

  get "affiliate_program" => "affilate_programs#affiliate_program"
  get "affilate_records" => "affilate_programs#affilate_records"
  get "transfer_commission" => "affilate_programs#transfer_commission"
  


  



  get "homepage" => "users#homepage"
  get "activate_account" => "user_infos#activate_account"

  get "send2fasms" => "user_infos#send2fasms"
  get "send2favoice" => "user_infos#send2favoice"
  get "resendsms" => "user_infos#resendsms"
  get "verifysms_code" => "user_infos#verifysms_code"

  
  
  match 'reset_expired_password', to: 'users#reset_expired_password', via: %i(get patch post)

  get "user_log" => "watchdogs#user_log"
  get "active_sessions" => "logins#active_sessions"
  get "send_confirmation_email" => "users#send_confirmation_email"
  get "generate_qr_code" => "users#generate_qr_code"
  get "change_two_factor" => "users#change_two_factor"
  get "send_confirmation_mail" => "users#send_confirmation_mail"
  get "confirm_google_code" => "users#confirm_google_code"
  # get "set_otp_code" => "users#set_otp_code"
  get "affilate-program/:through/:refered_by" => "affilate_programs#set_invitation_code"
  post "send_invitation_email" => "affilate_programs#send_invitation_email"
  get "edit_password/:id" => "users#edit_password" , :as => "edit_password" 
  get "error_page" => "logins#error_page"
  get "error" => "errors_logs#error"
  get "lock_page" => "logins#lock_page"
  post "lock_page" => "logins#check_to_unlock"
  # resources :cards
  #get "buy_card" => "cards#buy_card"
  get "user_cards" => "cards#user_cards"
  get "remittance" => "cards#remittance"
  get "payment_method" => "cards#payment_method"
  get "payment_data" => "cards#payment_data"
  post "pay_operation" => "cards#pay_operation"
  get "paypalurl" => "cards#paypalurl"
  get "upload_payment_data" => "cards#upload_payment_data"
  post "upload_payment_data" => "cards#upload_payment_data"
  get "charging_card" => "cards#charging_card"
  post "charging_card" => "cards#charging_card_post"
  get "check_dosite" => "cards#check_dosite"
  
  
  
  # resources :cards_categories
  get "display_cards_categories" => "cards_categories#display_cards_categories"
  resources :addresses, :except => [:new, :edit, :show]
  post "update_address" => "addresses#update_address"
  get "user_addresses" => "addresses#user_addresses"
  resources :user_wallets
  get "transfer_balance" => "user_wallets#transfer_balance"
  post "transfer_balance" => "user_wallets#transfer_balancepost"
  get "send_sms" => "user_wallets#send_sms"
  post "send_sms_post" => "user_wallets#send_sms_post"
  post "verifysms_post" => "user_wallets#verifysms_post"
  get "verifysms" => "user_wallets#verifysms"
  get "user_wallet_balance" => "user_wallets#user_wallet_balance"
  get "confirm_transfer" => "user_wallets#confirm_transfer"
  get "refund_transfer" => "user_wallets#refund_transfer"
  get "check_receiver" => "user_wallets#check_receiver"
  resources :notifications
  resources :notifications_settings
  get "user_notifications" => "notifications#user_notifications"
  get "search_notifications" => "notifications#search"
  get "add_defualt_notifications" => "notifications_settings#add_defualt_notifications"
  get "user_notifications_setting" => "notifications_settings#user_notifications_setting"
  resources :uploads
  resources :money_ops
  get "paypal" => "money_ops#paypal"
  post "paypal_post" => "money_ops#paypal_post"
  get "paypalret" => "money_ops#paypalconfirm"
  post "paypal_ipn" => "money_ops#paypal_ipn"

  get "perfectmoney" => "money_ops#perfectmoney"
  post "perfectmoneyerror" => "money_ops#perfectmoneyerror"
  post "perfectmoney" => "money_ops#perfectmoneypost"

  post "call_coinmoney" => "money_ops#call_coinmoney"
  

  get "coinmoney" => "money_ops#coinmoney"
  post "coinmoney" => "money_ops#coinmoney_post"
  resources :users_wallets_transfers

  get "withdraw_op" => "money_ops#withdraw_op"
  post "withdraw_op" => "money_ops#withdrawpost"
  get "new_transaction"=>"money_ops#new_transaction"
  
  resources :ticket_departments
  resources :tickets, :except => [:new, :edit, :update]
  post 'tickets/reply' => 'tickets#create_reply'
  get "bank_data" => "money_ops#bank_data"
  get "close_ticket" => "tickets#close_ticket"
  get "report_ticket" => "tickets#report_ticket"
  post "evaluate_ticket" => "tickets#evaluate_ticket"
  
  resources :withdraws
  resources :audit_logs, :only => [:create]
  resources :quick_payments
  get "fast_pay/:slug" => "quick_payments#fast_pay"
  post "fast_pay" => "quick_payments#fast_pay_post"
  get "trust_user" => "quick_payments#trust_user"
  get "link_check" => "quick_payments#link_check"
  resources :user_announcements
  resources :blogs_categories
  resources :payers_blogs
  get "users_blogs" => "payers_blogs#users_blogs"
  get "catblogs" => "payers_blogs#catblogs"
  get "display_blog" => "payers_blogs#display_blog"
  get "blogs_sitemap.xml" => "payers_blogs#sitemap", :format => "xml", :as => :sitemap
  get "search_blog" => "payers_blogs#search_blog"
  post "search_blog_post" => "payers_blogs#search_blog_post"
  

app/controllers/nationalid_verifications_controller.rb
class NationalidVerificationsController < ApplicationController
  before_action :set_nationalid_verification, only: [:show, :edit, :update, :destroy]
  before_action :require_login

  # create new National Id Verification
  # @param [String] legal_name
  # @param [Integer] national_id
  # @param [Integer] document_type
  # @param [Date] issue_date
  # @param [Date] expire_date
  # @param [Blob] attachment1
  # @param [Blob] attachment2
  # @return [Integer] id
  # @return [String] username
  # @return [String] legal_name
  # @return [Integer] national_id
  # @return [Integer] document_type
  # @return [Date] issue_date
  # @return [Date] expire_date
  # @return [Blob] attachment1
  # @return [Blob] attachment2
  # @return [Integer] status
  # @return [datetime] created_at
  # @return [datetime] updated_at
  def create
    begin
      @current_user_verification = NationalidVerification.where("user_id =?", current_user.id.to_i).first
      if @current_user_verification != nil
        redirect_to root_path , notice: "not allowed"
      else
        @nationalid_verification = NationalidVerification.new(nationalid_verification_params)
        @nationalid_verification.user_id = current_user.id
        if params[:nationalid_verification][:legal_name] != "" and params[:nationalid_verification][:national_id] != "" and params[:nationalid_verification][:document_type] != "" and params[:nationalid_verification][:issue_date] != "" and params[:nationalid_verification][:expire_date] != "" and params[:nationalid_verification][:images] != nil
          @nationalid_verification.status = "Pending"
        else
          @nationalid_verification.status = "UnVerified"
        end
        if params[:nationalid_verification][:legal_name]
          @legal_name = params[:nationalid_verification][:legal_name]
          current_user.update(firstname: @legal_name.partition(" ").first, lastname: @legal_name.partition(" ").last)
        end
        respond_to do |format|
          if @nationalid_verification.save
            if @nationalid_verification.status == "Pending"
              format.html { redirect_to activate_account_path }
            else
              format.html { redirect_to dashboard_path }
            end
            format.json { render :show, status: :created, location: @nationalid_verification }
            AuditlogJob.perform_async(user_id: current_user.id, user_name: current_user.uuid, action_type: "Upload Nationalid verifications", action_meta: "Nationalid verification was successfully created.", ip: request.env['REMOTE_ADDR'])
          else
            format.html { redirect_to activate_account_path, notice: @nationalid_verification.errors }
            format.json { render json: @nationalid_verification.errors, status: :unprocessable_entity }
          end
        end
      end
    rescue =>e
      @code = SecureRandom.hex(6)
      @log =  ErrorsLog.create(:user_id => current_user.id,:user_type => 2,:message => e.message.to_s,:code => @code.to_s) 
      redirect_to controller: 'errors_logs', action: 'error', id: @log.id    
    end
  end

  # edit National Id Verification,
  # only admins can edit status and note.
  # @param [String] legal_name
  # @param [Integer] national_id
  # @param [Integer] document_type
  # @param [Date] issue_date
  # @param [Date] expire_date
  # @param [Blob] attachment1
  # @param [Blob] attachment2
  # @param [Integer] status
  # @param [String] note
  # @return [Integer] id
  # @return [String] username
  # @return [String] legal_name
  # @return [Integer] national_id
  # @return [Integer] document_type
  # @return [Date] issue_date
  # @return [Date] expire_date
  # @return [Blob] attachment1
  # @return [Blob] attachment2
  # @return [Integer] status
  # @return [String] note
  # @return [datetime] created_at
  # @return [datetime] updated_at
  def update
    begin
      if (@nationalid_verification.status == "Verified") or (current_user.id != @nationalid_verification.user_id.to_i)
        redirect_to root_path , notice: "not allowed" 
      else
        if params[:nationalid_verification][:legal_name] != "" and params[:nationalid_verification][:national_id] != "" and params[:nationalid_verification][:document_type] != "" and params[:nationalid_verification][:issue_date] != "" and params[:nationalid_verification][:expire_date] != "" and ( (params[:nationalid_verification][:images] != nil) or (@nationalid_verification.images.attached? == true))
          @nationalid_verification.status = "Pending"
        else
          @nationalid_verification.status = "UnVerified"
        end
        if params[:nationalid_verification][:legal_name]
          @legal_name = params[:nationalid_verification][:legal_name]
          if @legal_name.split(" ")[0] == "عبد" or @legal_name.split(" ")[0] == "abd"
            current_user.update(firstname: @legal_name.split(" ")[0] + " " + @legal_name.split(" ")[1] , lastname: @legal_name.split(' ')[2..-1].join(' '))
          else
            current_user.update(firstname: @legal_name.partition(" ").first, lastname: @legal_name.partition(" ").last)
          end
        end
        respond_to do |format|
          if @nationalid_verification.update(nationalid_verification_params)
            if @nationalid_verification.status == "Pending"
              format.html { redirect_to activate_account_path }
            else
              format.html { redirect_to dashboard_path }
            end
            format.json { render :show, status: :ok, location: @nationalid_verification }
            AuditlogJob.perform_async(user_id: current_user.id, user_name: current_user.uuid, action_type: "Edit Nationalid verifications", action_meta: "Nationalid verification was successfully updated.", ip: request.env['REMOTE_ADDR'])
          else
            format.html { redirect_to activate_account_path, notice: @nationalid_verification.errors }
            format.json { render json: @nationalid_verification.errors, status: :unprocessable_entity }
          end
        end
      end
    rescue =>e
      @code = SecureRandom.hex(6)
      @log =  ErrorsLog.create(:user_id => current_user.id,:user_type => 2,:message => e.message.to_s,:code => @code.to_s) 
      redirect_to controller: 'errors_logs', action: 'error', id: @log.id    
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_nationalid_verification
      @nationalid_verification = NationalidVerification.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def nationalid_verification_params
      params.require(:nationalid_verification).permit(:user_id, :legal_name, :national_id, :document_type, :issue_date, :expire_date, :status, :note, :attachment1, :attachment2, images: [])
    end
end

app/helpers/nationalid_verifications_helper.rb
module NationalidVerificationsHelper
end

app/views/nationalid_verifications/_form.html.erb
<% if (@user_infos and @user_infos.mobile == 1 and  (@current_user_nationalid == nil or (@current_user_nationalid and @current_user_nationalid.status == "UnVerified"))) %>
  <fieldset id="active-id-step" class="step-box step-active-box" style="display: block; left: 0%;  right: 0%; opacity: 1;">                
<% else %>
  <fieldset id="active-id-step" class="step-box step-active-box" style="display: none; left: 0%; right: 0%; opacity: 0;">               
<% end %>
    <%= form_with(model: nationalid_verification, local: true,:html => {:id => 'natid_form', :multipart => true }) do |form| %>
      <h2><span>3</span><%= t('nationalid_verifications.confrim_identity')%></h2>
      <p class="margin-b-20"><%= t('nationalid_verifications.upload_valid_id') %></p>
      <div class="row margin-b-20">
        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12 mobile-margin-b-20">
          <div class="inputstyle inputstyle-span selectstyle">
            <span class="text-span"><%= t('nationalid_verifications.identity_type')%></span>
            <%= form.select(:document_type, options_for_select([[t('nationalid_verifications.personal_identity'),"NationalId_Card"],[t('nationalid_verifications.passport'),"Passport"],[t('nationalid_verifications.driving_license'),"Driving_License"]], :selected => form.object.document_type), {},:include_blank =>  'choose from list')%>
          </div>
          <span class="col-lg-5" id="doc_msg" style="color:red; display:none"><%= t('nationalid_verifications.choose_the_document')%></span>
        </div>
        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
          <label class="payers-fileinput button-3">
            <span data-default='Choose file'><%= t('nationalid_verifications.upload_image')%></span>
            <%= form.file_field :images, multiple: true, accept: 'image/png,image/jpeg, image/jpg' %>
          </label>
          <span class="steps-p" id="img_msg" style="color:red; display:none;"><%= t('nationalid_verifications.upload_document')%></span>
        </div>
      </div>
      <div class="row margin-b-20">
        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12 mobile-margin-b-20">
          <div class="inputstyle">
            <%= form.text_field :legal_name, placeholder: t('nationalid_verifications.name'), :autocomplete => "off" %>
          </div>
          <span id="name_msg" class="steps-p" style="color:red; display:none;"></span>
        </div>
        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
          <div class="inputstyle">
            <%= form.text_field :national_id, placeholder: t('nationalid_verifications.identity_number'), :autocomplete => "off" %>
          </div>
          <span class="steps-p" id="natid_msg" style="color:red; display:none;"></span>
        </div>
      </div>
      <div class="row margin-b-20">
        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12 mobile-margin-b-20">
          <div class="inputstyle relative-box selectstyle inputstyle-span">
            <span class="text-span"><%= t('nationalid_verifications.creation_date') %></span>
            <%# form.date_select :issue_date,  {:placeholder => 'اليوم / الشهر / السنة'} %>
            <%# form.text_field :issue_date,  {:class => "date", :placeholder => 'اليوم    /   الشهر    /   السنة', :autocomplete => "off"} %>
            <%= form.text_field :issue_date,  {:class => "dateplaceholder", :placeholder =>  t('nationalid_verifications.date'), :autocomplete => "off"} %>
          </div>
          <span class="steps-p" id="issue_msg" style="color:red; display:none;"></span>
        </div>
        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
          <div class="inputstyle relative-box selectstyle inputstyle-span">
            <span class="text-span"><%= t('nationalid_verifications.expiration_date') %></span>
            <%# form.date_select :expire_date,  {:placeholder => 'اليوم /الشهر / السنة'} %>
            <%# form.text_field :expire_date,  {:class => "date", :placeholder => 'اليوم    /   الشهر    /   السنة', :autocomplete => "off"} %>
            <%= form.text_field :expire_date,  {:class => "dateplaceholder", :placeholder => t('nationalid_verifications.date'), :autocomplete => "off"} %>
          </div>
          <span class="steps-p" id="expire_msg" style="color:red; display:none;"></span>
        </div>
      </div>
      <input id="verify_natid" type="button" class="button-1" value="<%= t('nationalid_verifications.activate')%>" />
    <% end %>
  </fieldset>

  

app/views/nationalid_verifications/_new.html.erb
<%= render 'form', nationalid_verification: @nationalid_verification %>

<%= link_to 'Back', nationalid_verifications_path %>

app/views/nationalid_verifications/edit.html.erb
<%= render 'form', nationalid_verification: @nationalid_verification %>

<%= link_to 'Show', @nationalid_verification %> |
<%= link_to 'Back', nationalid_verifications_path %>

app/views/nationalid_verifications/index.html.erb
<!-- ############ PAGE START-->
<div class="padding">
  <div class="box">
    <div class="box-header">
      <h2>Nationalid Verifications</h2>
      <small>.......</small>
    </div>
    <div class="box-body">
      Search: <input id="filter" type="text" class="form-control input-sm w-auto inline m-r"/> 
    </div>
    <div>
      <table class="table m-b-none" ui-jp="footable" data-filter="#filter" data-page-size="5">
        <thead>
          <tr>
              <th>
              UserName
              </th>
              <th data-hide="phone">
              Status
              </th>
          </tr>
        </thead>
        <tbody>
        <% @nationalid_verifications.each do |nationalid_verification| %>
          <tr>
              <td><%= nationalid_verification.user.firstname + " " + nationalid_verification.user.lastname %></td> 
              <% if nationalid_verification.status == "Verified"  %>
                <td data-value="1"><span class="label success" title="Active">Verified</span></td>
              <% else  %>
                <td data-value="2"><span class="label" title="Disabled">UnVerified</span></td>
              <% end %>
              <td><%= link_to 'Show', nationalid_verification, :class => 'btn btn-sm info' %></td>   
              <% if current_user and current_user.roleid == 1 %>
                    <td><%= link_to 'Edit', edit_nationalid_verification_path(nationalid_verification), :class => 'btn btn-sm warning' %></td>       
              <% end %>           
          </tr>
        <% end %>
          
        </tbody>
        <tfoot class="hide-if-no-paging">
          <tr>
              <td colspan="5" class="text-center">
                  <ul class="pagination"></ul>
              </td>
          </tr>
        </tfoot>
      </table>
    </div>
  </div>
</div>



<!-- ############ PAGE END-->

app/views/nationalid_verifications/show.html.erb
<div class="padding">  
      <div class="box">
        <div class="box-header">
          <span class="label danger pull-right"><%= @nationalid_verification.id %></span>
          <h3> National ID Verification Details</h3>
        </div>
        <table class="table">
          <thead>
            <tr>
              <th>User</th>
              <td><%= @nationalid_verification.user.firstname + " " + @nationalid_verification.user.lastname  %></td>
            </tr>
          </thead>
          <tbody>
            <tr>
              <th>Legal Name</th>
              <td> <%= @nationalid_verification.legal_name %></td>
            </tr>
            <tr>
              <th>National ID</th>
              <td> <%= @nationalid_verification.national_id %></td>
            </tr>
            <tr>
              <th>Document Type</th>
              <td> <%= @nationalid_verification.document_type  %></td>
            </tr>
            <tr>
            <th>Issue Date</th>
            <td> <%= @nationalid_verification.issue_date %></td>
          </tr>
          <tr>
            <th>Expire date</th>
            <td> <%= @nationalid_verification.expire_date %></td>
          </tr>
          <% if @nationalid_verification.attachment1.attached? %>
            <tr>
              <th>attachment</th>
              <td><%= image_tag @nationalid_verification.attachment1.variant(resize: "100x100")  %></td>
            </tr>
          <% end %>
          <% if @nationalid_verification.attachment2.attached? %>
            <tr>
              <th>attachment2</th>
              <td><%= image_tag @nationalid_verification.attachment2.variant(resize: "100x100")  %></td>
            </tr>  
          <% end %>

          <% if @nationalid_verification.images.attached? %>
            <tr>
                    <th>images</th> 
               <% @nationalid_verification.images.each do |image| %>
               <td>
                  <%= image_tag image.variant(resize: "100x100")  %>
               </td>
               </tr>
           <% end %>
          <% end %>

            <tr>
              <th>Status</th>
              <td> <%= @nationalid_verification.status %></td>
            </tr>


          <% if @nationalid_verification.note != nil and @nationalid_verification.note != "" %>
            <tr>
              <th>Note </th>
              <td> <%= @nationalid_verification.note %></td>
            </tr>
          <% end %>         
          </tbody>
        </table>
      </div>
</div>