config/routes.rb
Rails.application.routes.draw do

  resources :errors_logs, :only => [:create]
  resources :settings
  resources :users_banks, :except => [:edit, :show]
  resources :banks, :only => [:create]
  resources :selfie_verifications, :only => [:create, :update]
  resources :address_verifications, :only => [:create, :update]
  resources :nationalid_verifications, :only => [:create, :update]
  resources :user_infos, :only => [:create]
  namespace :api, defaults: {format: 'json'} do
    namespace :v1 do
      resources :users_banks
      resources :watchdogs
      resources :users
      resources :countries
      resources :affilate_programs
      resources :selfie_verifications, :except => [:index, :destroy]
      resources :address_verifications, :except => [:index, :destroy]
      resources :nationalid_verifications, :except => [:index, :destroy]
      resources :translations
      post "users/create" => "users#create"
      get "homepage" => "users#homepage"
      post "confirmmail" => "users#confirmmail"
      post "resend_confirmmail" => "users#resend_confirmmail"
      get "two_factor" => "users#get_two_factor"
      post "two_factor" => "users#post_two_factor"
      get "send_confirmation_email" => "users#send_confirmation_email"
      get "generate_qr_code" => "users#generate_qr_code"
      get "confirm_google_code" => "users#confirm_google_code"
      get "user_log" => "watchdogs#user_log"
      get "active_sessions" => "logins#active_sessions"
      post 'auth_user' => 'authentication#authenticate_user'
      post "unlockaccount" => "authentication#unlockaccount"
      post "send_invitation_email" => "affilate_programs#send_invitation_email"
      post 'getEditToken' => 'authentication#getEditToken'
      # resources :cards
      #get "buy_card" => "cards#buy_card" 
      # resources :cards_categories
      get "display_cards_categories" => "cards_categories#display_cards_categories"
      resources :addresses, :except => [:new, :edit, :show]
      post "update_address" => "addresses#update_address"
      get "user_addresses" => "addresses#user_addresses"
      resources :user_wallets
      get "transfer_balance" => "user_wallets#transfer_balance"
      post "transfer_balance" => "user_wallets#transfer_balancepost"
      get "send_sms" => "user_wallets#send_sms"
      post "send_sms_post" => "user_wallets#send_sms_post"
      post "verifysms_post" => "user_wallets#verifysms_post"
      get "verifysms" => "user_wallets#verifysms" 
      get "user_wallet_balance" => "user_wallets#user_wallet_balance"
      resources :notifications
      resources :notifications_settings
      get "user_notifications" => "notifications#user_notifications"
      get "search_notifications" => "notifications#search"
      get "add_defualt_notifications" => "notifications_settings#add_defualt_notifications"
      resources :uploads
      resources :money_ops
      resources :ticket_departments
      resources :tickets, :except => [:new, :edit, :update]
      post 'tickets/reply' => 'tickets#create_reply'
      get "close_ticket" => "tickets#close_ticket"
      get "report_ticket" => "tickets#report_ticket"
      post "evaluate_ticket" => "tickets#evaluate_ticket"
      resources :payers_blogs
      get "users_blogs" => "payers_blogs#users_blogs"
      get "catblogs" => "payers_blogs#catblogs"
      get "display_blog" => "payers_blogs#display_blog"
      get "blogs_sitemap.xml" => "payers_blogs#sitemap", :format => "xml", :as => :sitemap
      get "payers_blogs_categories" => "payers_blogs#payers_blogs_categories"
      resources :settings
      get "mail_setting" => "settings#mail_setting"
      
    end
  end









  resources :affilate_programs, :only => [:create, :destroy]
  #resources :countries, :only => [:index, :show]
  resources :logins, :only => [:create, :destroy]
  resources :verifications, :only => [:create, :update, :destroy]
  resources :watchdogs, :only => [:create, :show, :destroy]
  resources :users, :except => [:index, :edit]
  # root "users#dashboard"
  root "users#homepage"
  get "confirmmail" => "users#confirmmail"
  get "unlockaccount" => "users#unlockaccount"
  get "two_factor" => "users#get_two_factor"
  post "two_factor" => "users#post_two_factor"
  get "resend_two_factor" => "users#resend_two_factor"
  get "dashboard" => "users#dashboard"
  get "destroy_all_sessions" => "clearance/sessions#destroy_all_sessions"
  get "destroy_one_session" => "clearance/sessions#destroy_one_session"
  
  match 'pass_to_security_settings', to: 'users#pass_to_security_settings', via: %i(get patch post)
  get "secure_my_account" => "users#secure_my_account"
  
  get "check_mail" => "users#check_mail"
  get "check_phone" => "users#check_phone"
  get "check_country_code" => "users#check_country_code"
  get "after_sign_up" => "users#after_sign_up"
  get "resend_confirmation_mail" => "users#resend_confirmation_mail"

  get "affiliate_program" => "affilate_programs#affiliate_program"
  get "affilate_records" => "affilate_programs#affilate_records"
  get "transfer_commission" => "affilate_programs#transfer_commission"
  


  



  get "homepage" => "users#homepage"
  get "activate_account" => "user_infos#activate_account"

  get "send2fasms" => "user_infos#send2fasms"
  get "send2favoice" => "user_infos#send2favoice"
  get "resendsms" => "user_infos#resendsms"
  get "verifysms_code" => "user_infos#verifysms_code"

  
  
  match 'reset_expired_password', to: 'users#reset_expired_password', via: %i(get patch post)

  get "user_log" => "watchdogs#user_log"
  get "active_sessions" => "logins#active_sessions"
  get "send_confirmation_email" => "users#send_confirmation_email"
  get "generate_qr_code" => "users#generate_qr_code"
  get "change_two_factor" => "users#change_two_factor"
  get "send_confirmation_mail" => "users#send_confirmation_mail"
  get "confirm_google_code" => "users#confirm_google_code"
  # get "set_otp_code" => "users#set_otp_code"
  get "affilate-program/:through/:refered_by" => "affilate_programs#set_invitation_code"
  post "send_invitation_email" => "affilate_programs#send_invitation_email"
  get "edit_password/:id" => "users#edit_password" , :as => "edit_password" 
  get "error_page" => "logins#error_page"
  get "error" => "errors_logs#error"
  get "lock_page" => "logins#lock_page"
  post "lock_page" => "logins#check_to_unlock"
  # resources :cards
  #get "buy_card" => "cards#buy_card"
  get "user_cards" => "cards#user_cards"
  get "remittance" => "cards#remittance"
  get "payment_method" => "cards#payment_method"
  get "payment_data" => "cards#payment_data"
  post "pay_operation" => "cards#pay_operation"
  get "paypalurl" => "cards#paypalurl"
  get "upload_payment_data" => "cards#upload_payment_data"
  post "upload_payment_data" => "cards#upload_payment_data"
  get "charging_card" => "cards#charging_card"
  post "charging_card" => "cards#charging_card_post"
  get "check_dosite" => "cards#check_dosite"
  
  
  
  # resources :cards_categories
  get "display_cards_categories" => "cards_categories#display_cards_categories"
  resources :addresses, :except => [:new, :edit, :show]
  post "update_address" => "addresses#update_address"
  get "user_addresses" => "addresses#user_addresses"
  resources :user_wallets
  get "transfer_balance" => "user_wallets#transfer_balance"
  post "transfer_balance" => "user_wallets#transfer_balancepost"
  get "send_sms" => "user_wallets#send_sms"
  post "send_sms_post" => "user_wallets#send_sms_post"
  post "verifysms_post" => "user_wallets#verifysms_post"
  get "verifysms" => "user_wallets#verifysms"
  get "user_wallet_balance" => "user_wallets#user_wallet_balance"
  get "confirm_transfer" => "user_wallets#confirm_transfer"
  get "refund_transfer" => "user_wallets#refund_transfer"
  get "check_receiver" => "user_wallets#check_receiver"
  resources :notifications
  resources :notifications_settings
  get "user_notifications" => "notifications#user_notifications"
  get "search_notifications" => "notifications#search"
  get "add_defualt_notifications" => "notifications_settings#add_defualt_notifications"
  get "user_notifications_setting" => "notifications_settings#user_notifications_setting"
  resources :uploads
  resources :money_ops
  get "paypal" => "money_ops#paypal"
  post "paypal_post" => "money_ops#paypal_post"
  get "paypalret" => "money_ops#paypalconfirm"
  post "paypal_ipn" => "money_ops#paypal_ipn"

  get "perfectmoney" => "money_ops#perfectmoney"
  post "perfectmoneyerror" => "money_ops#perfectmoneyerror"
  post "perfectmoney" => "money_ops#perfectmoneypost"

  post "call_coinmoney" => "money_ops#call_coinmoney"
  

  get "coinmoney" => "money_ops#coinmoney"
  post "coinmoney" => "money_ops#coinmoney_post"
  resources :users_wallets_transfers

  get "withdraw_op" => "money_ops#withdraw_op"
  post "withdraw_op" => "money_ops#withdrawpost"
  get "new_transaction"=>"money_ops#new_transaction"
  
  resources :ticket_departments
  resources :tickets, :except => [:new, :edit, :update]
  post 'tickets/reply' => 'tickets#create_reply'
  get "bank_data" => "money_ops#bank_data"
  get "close_ticket" => "tickets#close_ticket"
  get "report_ticket" => "tickets#report_ticket"
  post "evaluate_ticket" => "tickets#evaluate_ticket"
  
  resources :withdraws
  resources :audit_logs, :only => [:create]
  resources :quick_payments
  get "fast_pay/:slug" => "quick_payments#fast_pay"
  post "fast_pay" => "quick_payments#fast_pay_post"
  get "trust_user" => "quick_payments#trust_user"
  get "link_check" => "quick_payments#link_check"
  resources :user_announcements
  resources :blogs_categories
  resources :payers_blogs
  get "users_blogs" => "payers_blogs#users_blogs"
  get "catblogs" => "payers_blogs#catblogs"
  get "display_blog" => "payers_blogs#display_blog"
  get "blogs_sitemap.xml" => "payers_blogs#sitemap", :format => "xml", :as => :sitemap
  get "search_blog" => "payers_blogs#search_blog"
  post "search_blog_post" => "payers_blogs#search_blog_post"
  

app/models/affilate_program.rb
class AffilateProgram < ApplicationRecord
    belongs_to :user ,:foreign_key => "user_id"
    enum profit_source: { fb_referral: 1, tw_referral: 2, email_invite: 3, invitation_link: 4, commission_code: 5, insta_referral: 6  }

end

app/controllers/affilate_programs_controller.rb
class AffilateProgramsController < ApplicationController
  before_action :set_affilate_program, only: [:show, :edit, :update, :destroy]
  before_action :require_login , except: [:set_invitation_code]
  skip_before_action :check2fa ,only: [:set_invitation_code]
  skip_before_action :check_active_session ,only: [:set_invitation_code]
  skip_before_action :check_password_expiration ,only: [:set_invitation_code]

  def affiliate_program
    begin
      @user = current_user
      @affiliate_commission = AffilateProgram.where(refered_by: current_user.id).all    
      @valid_commission = @affiliate_commission.where(invitor_commission_status: true).sum(:invitor_commission)
      @latest_commission =  @affiliate_commission.where.not(invitor_commission: nil , invitor_commission: 0 ).last
      @total_commission = @affiliate_commission.where.not(invitor_commission: nil).sum(:invitor_commission)
    rescue =>e
      @code = SecureRandom.hex(6)
      @log =  ErrorsLog.create(:user_id => current_user.id,:user_type => 2,:message => e.message.to_s,:code => @code.to_s) 
      redirect_to controller: 'errors_logs', action: 'error', id: @log.id    
    end
  end

  def affilate_records
    begin
      @total_commission = AffilateProgram.where(refered_by: current_user.id).where.not(invitor_commission: nil,invitor_commission_status: nil).joins(:user).all    
      @commission_setting = Setting.where(:key => "invitor_commision").first
      render :layout => false
    rescue =>e
      @code = SecureRandom.hex(6)
      @log =  ErrorsLog.create(:user_id => current_user.id,:user_type => 2,:message => e.message.to_s,:code => @code.to_s) 
      redirect_to controller: 'errors_logs', action: 'error', id: @log.id    
    end
  end


  # when invited users click on invitation link which send to their mails,
  # they are redirected here and invitation code put in the session to be saved during registeration
  # @param [Integer] refered_by
  def set_invitation_code
    session[:refered_by] = params[:refered_by]
    session[:profit_source] = params[:through]
    redirect_to sign_up_path
  end


  # registered users can send invitation mail to other users
  # @param [String] email
  def send_invitation_email
    begin
      @email_to = params[:invitiation][:email]
      EmailJob.perform_async(user_mail:current_user,text:@email_to,subject:'send invitation')
      AuditlogJob.perform_async(user_id: current_user.id, user_name: current_user.uuid, action_type: "send invitation", action_meta: "send invitation.", ip: request.env['REMOTE_ADDR'])
      redirect_to affiliate_program_path 
    rescue =>e
      @code = SecureRandom.hex(6)
      @log =  ErrorsLog.create(:user_id => current_user.id,:user_type => 2,:message => e.message.to_s,:code => @code.to_s) 
      redirect_to controller: 'errors_logs', action: 'error', id: @log.id    
    end
  end

  def transfer_commission
    begin
      @balance = params[:balance].to_f
      @user_wallet = UserWallet.where(user_id: current_user.id).first
      if (@user_wallet and @balance > 0 and @balance != nil )
        @user_wallet.update(amount: @user_wallet.amount.to_f + @balance)
        AffilateProgram.where(refered_by: current_user.id, invitor_commission_status: true).update_all(invitor_commission_status: false)
        MoneyOp.where(user_id: current_user.id, optype: 5, status: 0).update_all(status: 1)
        AuditlogJob.perform_async(user_id: current_user.id, user_name: current_user.uuid, action_type: "withdraw commission", action_meta: "transfer commission to wallet balance", ip: request.env['REMOTE_ADDR'])
        access_notification("Marketing Profits", "You have been Added $ #{@balance.to_f} From Marketing Profits To Your Wallet Balance Successfully", "affilate_programs", @balance)
        render :json => { 'result': "done" }
      end
    rescue =>e
      @code = SecureRandom.hex(6)
      @log =  ErrorsLog.create(:user_id => current_user.id,:user_type => 2,:message => e.message.to_s,:code => @code.to_s) 
      redirect_to controller: 'errors_logs', action: 'error', id: @log.id    
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_affilate_program
      @affilate_program = AffilateProgram.find(params[:id])
    end

    def access_notification(title, smstext, control, amount)

      @user = current_user
      @title = title
      @smstext = smstext
      @amount = amount

      @user_notification_setting = NotificationsSetting.where(user_id: @user.id.to_i).first      

      Notification.create(user_id: @user.id ,title: @title, description: @smstext , notification_type: @user_notification_setting.money_transactions, controller: control)
        @userphone = @user.country.Phone_code.to_s + @user.telephone
      if @user_notification_setting.money_transactions == 3
        SMSNotification.sms_notification_setting(@userphone, @smstext)
        SmsLog.create(:user_id => @user.id, :pinid => @smstext,:status => 1,:sms_type => 3)
        EmailNotification.email_notification_setting(user_mail:@user.email, subject:@title, text: smstext)
      elsif @user_notification_setting.money_transactions == 2
        SMSNotification.sms_notification_setting(@userphone, @smstext)
        SmsLog.create(:user_id => @user.id, :pinid => @smstext,:status => 1, :sms_type => 3)
      elsif @user_notification_setting.money_transactions == 1
        EmailNotification.email_notification_setting(user_mail:@user.email, subject:@title, text: smstext)
      end

    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def affilate_program_params
      params.require(:affilate_program).permit(:user_id, :refered_by, :invitor_commission, :invitor_commission_status, :profit_source)
    end
end

app/helpers/affilate_programs_helper.rb
module AffilateProgramsHelper
end

app/views/affilate_programs/_form.html.erb
<%= form_with(model: affilate_program, local: true) do |form| %>
  <% if affilate_program.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(affilate_program.errors.count, "error") %> prohibited this affilate_program from being saved:</h2>

      <ul>
      <% affilate_program.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.number_field :user_id %>
  </div>

  <div class="field">
    <%= form.label :refered_by %>
    <%= form.number_field :refered_by %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/affilate_programs/affiliate_program.html.erb
<!-- Title Page -->
<div class="head-page title-page custom-container-2">
  <div class="container">
    <div class="row">
      <div class="col-xs-12">
        <h1><%= t('affilate_programs.account_Settings')%></h1>
        <p><%= t('affilate_programs.brief_summary_of_your_balance_urgent_matters_and_last_transaction')%></p>
      </div>
    </div>
  </div>
</div>
<!-- Title Page -->

<!-- Dashboard -->
<div class="custom-container-2">
  <div class="container">
    <div class="row">
      <%= render :partial => 'layouts/sidemenu' %>
      <div class="col-lg-9 col-md-9 col-sm-8 col-xs-12">
        <div class="row">
          <div class="col-xs-12">
            <div class="white-box user-setting-box user-affiliate-program relative-box margin-b-25">
              <h3><%= t('affilate_programs.status_of_your_commission_marketing_earnings')%></h3>
              <div class="user-affiliate-blocks">
                <div class="user-affiliate-block">
                  <h4><%= t('affilate_programs.profits_can_be_withdrawn')%></h4>
                  <p><%= t('affilate_programs.Added_to_your_balance')%></p>
                  <h5>$<%= @valid_commission %></h5>
                </div>
                <div class="user-affiliate-block">
                  <h4><%= t('affilate_programs.latest_profits_added')%></h4>
                  <% if @latest_commission != nil %>
                    <p><%= t('affilate_programs.of_1_registration')%> <%= @latest_commission.created_at.strftime(' %d/%m/%Y ') %></p>
                    <h5>$<%= @latest_commission.invitor_commission%></h5>
                  <% else %>
                    <p><%= t('affilate_programs.of_the_recording')%></p>
                    <h5>$<%= "0.0" %></h5>
                  <% end %>
                </div>
                <div class="user-affiliate-block">
                  <h4><%= t('affilate_programs.total_Profits')%></h4>
                  <p><%= t('affilate_programs.of_all_previous_and_current_conversions')%></p>
                  <h5>$<%= @total_commission %></h5>
                </div>
              </div>
              <div class="row transfer-affiliate">
                <div class="col-xs-12">
                  <button id="transfer_profits" class="button-3"><%= t('affilate_programs.send_profits')%></button>
                  <p><%= t('affilate_programs.after_transferring')%></p>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col-lg-7 col-md-7 col-sm-12 col-xs-12">
            <div class="white-box-2 user-setting-box main-affiliate-box user-setting-p margin-b-25">
              <p class="margin-b-25"><%= t('affilate_programs.With_payers_Commission')%></p>
              <p class="margin-b-25"><%= t('affilate_programs.every_time')%></p>
              <p class="margin-b-20"><%= t('affilate_programs.use_one')%></p>
              <div class="affiliate-box">
                <h4><%= t('affilate_programs.your_Marketing')%></h4>
                <div class="inputstyle inputstyle-span inputarial">
                  <span class="text-span"><%= t('affilate_programs.code')%></span>
                  <input type="text" name="" placeholder="<%= @user.invitation_code %>" disabled>
                </div>
              </div>
              <div class="affiliate-box">
                <h4><%= t('affilate_programs.affilate_link')%></h4>
                <div class="inputstyle inputstyle-span inputarial">
                  <span class="text-span"><%= t('affilate_programs.affilate_link')%></span>
                  <input type="text" name="" placeholder="<%= 'https://payers-design-2019.herokuapp.com/affilate-program/invitation_link/' + @user.invitation_code %>" disabled>
                </div>
              </div>
              <%= form_for :invitiation, url: send_invitation_email_path do |form| %>
                <div class="affiliate-box">
                  <h4><%= t('affilate_programs.send_invitation')%></h4>
                  <div class="row">
                    <div class="col-lg-8 col-md-7 col-sm-12 col-xs-12">
                      <div class="inputstyle inputstyle-span inputarial">
                        <span class="text-span"><%= t('affilate_programs.email')%></span>
                        <%= form.text_field :email, :placeholder => "myfriend@gmail.com" %>
                      </div>
                    </div>
                    <div class="col-lg-4 col-md-5 col-sm-12 col-xs-12 send-affiliate text-left">
                      <button type="submit" class="button-3"><%= t('affilate_programs.send')%></button>
                    </div>
                  </div>
                </div>
              <% end %>
              <div class="affiliate-box social-affiliate-box">
                <h4><%= t('affilate_programs.share_link')%></h4>
                <!-- <a target="_blank" href="<%= 'https://instagram.com/share?url=https://payers-design-2019.herokuapp.com/affilate-program/fb_referral/' + @user.invitation_code %>" title="Instagram"><i class="fa fa-instagram" aria-hidden="true"></i></a> -->
                <% @current_login = Login.where(:user_id => current_user.id, :device_id => cookies[:device_id]).first %>
                <% if @current_login.user_agent !~ /\b(Android|iPhone|iPad|Windows Phone|Opera Mobi|Kindle|BackBerry|PlayBook)\b/i %>
                  <a href="https://web.whatsapp.com/send?text=<%= 'https://payers-design-2019.herokuapp.com/affilate-program/fb_referral/' + @user.invitation_code %>"  onclick="window.open(this.href, 'whatsapp-share-dialog','left=20,top=20,width=400,height=400,toolbar=1,resizable=0'); return false;" data-action="share/whatsapp/share"><i class="fa fa-whatsapp" style="color:#4FCE5D" aria-hidden="true"></i></a>
                <% else %>
                  <a href="whatsapp://send?text=<%= 'https://payers-design-2019.herokuapp.com/affilate-program/fb_referral/' + @user.invitation_code %>" onclick="window.open(this.href, 'whatsapp-share-dialog','left=20,top=20,width=400,height=400,toolbar=1,resizable=0'); return false;"><i class="fa fa-whatsapp" aria-hidden="true"></i></a>
                <% end %>
                <a  href="<%= 'https://www.facebook.com/share.php?u=https://payers-design-2019.herokuapp.com/affilate-program/fb_referral/' + @user.invitation_code %>" title="Facebook" onclick="window.open(this.href, 'facebook-share-dialog','left=20,top=20,width=400,height=400,toolbar=1,resizable=0'); return false;"><i class="fa fa-facebook-official" aria-hidden="true" ></i></a>
                <a href="<%= 'http://twitter.com/home?status=https://payers-design-2019.herokuapp.com/affilate-program/tw_referral/' + @user.invitation_code %>" title="Twitter" onclick="window.open(this.href, 'twitter-share-dialog','left=20,top=20,width=400,height=400,toolbar=1,resizable=0'); return false;"><i class="fa fa-twitter" aria-hidden="true"></i></a>
              </div>
            </div>
          </div>
          <div class="col-lg-5 col-md-5 col-sm-12 col-xs-12">
            <div class="white-box-2 user-setting-box user-setting-p margin-b-25">
              <h3><%= t('affilate_programs.send')%></h3>
              <p class="margin-b-30"><%= t('affilate_programs.all_earnings')%></p>
              <button onclick="location.href = '/affilate_records';" class="button-3"><%= t('affilate_programs.affilate_profits')%></button>
            </div>
            <div class="white-box-2 user-setting-box user-setting-p margin-b-25">
              <h3><%= t('affilate_programs.rules_and')%></h3>
              <p><%= t('affilate_programs.the_commission')%></p>
            </div>
            <div class="white-box-2 user-setting-box user-setting-p margin-b-25">
              <h3><%= t('affilate_programs.act_your')%></h3>
              <p><%= t('affilate_programs.you_can_dispose')%></p>
            </div>
            <div class="white-box-2 user-setting-box user-setting-p margin-b-25">
              <h3><%= t('affilate_programs.twisted_advertising')%></h3>
              <p><%= t('affilate_programs.Please_note')%></p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<!-- Dashboard -->
<script src="/assets/js/jquery.min.js"></script>
<script>
$(document).ready(function()
    {
      $('#transfer_profits').click(function()
        {
          $("#transfer_profits").attr("disabled", "disabled");
          var balance = '<%= @valid_commission %>';
          console.log(balance);
          if (balance > 0){
            $.ajax({
              type:'get',url:'/transfer_commission',data:{balance:balance},contentType: "application/json",dataType: "json",success: function(data){
                if (data.result == "done"){
                  setTimeout(function(){
                    location.reload();
                      }, 500);
                }
              }
            });
          }
        });
    });


</script>

app/views/affilate_programs/edit.html.erb
<h1>Editing Affilate Program</h1>

<%= render 'form', affilate_program: @affilate_program %>

<%= link_to 'Show', @affilate_program %> |
<%= link_to 'Back', affilate_programs_path %>

app/views/affilate_programs/index.html.erb
<!-- ############ PAGE START-->
<div class="padding">

  <div class="box">
    <div class="box-header">
      <h2>Affilate Programs</h2>
      <small>.......</small>
    </div>
    <div class="box-body">
      Search: <input id="filter" type="text" class="form-control input-sm w-auto inline m-r"/>
    </div>
    <div>
      <table class="table m-b-none" ui-jp="footable" data-filter="#filter" data-page-size="5">
        <thead>
          <tr>
              <th>
              UserName
              </th>
              <th data-hide="phone">
              Refered by
              </th>
          </tr>
        </thead>
        <tbody>
        <% @affilate_programs.each do |affilate_program| %>
          <tr>
              <td><%= affilate_program.user.firstname + " " + affilate_program.user.lastname %></td>
              <td><%= affilate_program.refered_by  %></td>
          </tr>
        <% end %>

        </tbody>
        <tfoot class="hide-if-no-paging">
          <tr>
              <td colspan="5" class="text-center">
                  <ul class="pagination"></ul>
              </td>
          </tr>
        </tfoot>
      </table>
    </div>
  </div>
</div>



<!-- ############ PAGE END-->

app/views/affilate_programs/new.html.erb
<h1>New Affilate Program</h1>

<%= render 'form', affilate_program: @affilate_program %>

<%= link_to 'Back', affilate_programs_path %>

app/views/affilate_programs/send_invitation_email.html.erb
<%= debug params[:invitiation][:email]%>

app/views/affilate_programs/show.html.erb
<%= debug @affilate_program.user%>
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @affilate_program.user.firstname + " " + @affilate_program.user.lastname %>
</p>

<p>
  <strong>Refered by:</strong>
  <%= @affilate_program.refered_by %>
</p>

<%= link_to 'Edit', edit_affilate_program_path(@affilate_program) %> |
<%= link_to 'Back', affilate_programs_path %>