config/routes.rb
Rails.application.routes.draw do

  resources :errors_logs, :only => [:create]
  resources :settings
  resources :users_banks, :except => [:edit, :show]
  resources :banks, :only => [:create]
  resources :selfie_verifications, :only => [:create, :update]
  resources :address_verifications, :only => [:create, :update]
  resources :nationalid_verifications, :only => [:create, :update]
  resources :user_infos, :only => [:create]
  namespace :api, defaults: {format: 'json'} do
    namespace :v1 do
      resources :users_banks
      resources :watchdogs
      resources :users
      resources :countries
      resources :affilate_programs
      resources :selfie_verifications, :except => [:index, :destroy]
      resources :address_verifications, :except => [:index, :destroy]
      resources :nationalid_verifications, :except => [:index, :destroy]
      resources :translations
      post "users/create" => "users#create"
      get "homepage" => "users#homepage"
      post "confirmmail" => "users#confirmmail"
      post "resend_confirmmail" => "users#resend_confirmmail"
      get "two_factor" => "users#get_two_factor"
      post "two_factor" => "users#post_two_factor"
      get "send_confirmation_email" => "users#send_confirmation_email"
      get "generate_qr_code" => "users#generate_qr_code"
      get "confirm_google_code" => "users#confirm_google_code"
      get "user_log" => "watchdogs#user_log"
      get "active_sessions" => "logins#active_sessions"
      post 'auth_user' => 'authentication#authenticate_user'
      post "unlockaccount" => "authentication#unlockaccount"
      post "send_invitation_email" => "affilate_programs#send_invitation_email"
      post 'getEditToken' => 'authentication#getEditToken'
      # resources :cards
      #get "buy_card" => "cards#buy_card" 
      # resources :cards_categories
      get "display_cards_categories" => "cards_categories#display_cards_categories"
      resources :addresses, :except => [:new, :edit, :show]
      post "update_address" => "addresses#update_address"
      get "user_addresses" => "addresses#user_addresses"
      resources :user_wallets
      get "transfer_balance" => "user_wallets#transfer_balance"
      post "transfer_balance" => "user_wallets#transfer_balancepost"
      get "send_sms" => "user_wallets#send_sms"
      post "send_sms_post" => "user_wallets#send_sms_post"
      post "verifysms_post" => "user_wallets#verifysms_post"
      get "verifysms" => "user_wallets#verifysms" 
      get "user_wallet_balance" => "user_wallets#user_wallet_balance"
      resources :notifications
      resources :notifications_settings
      get "user_notifications" => "notifications#user_notifications"
      get "search_notifications" => "notifications#search"
      get "add_defualt_notifications" => "notifications_settings#add_defualt_notifications"
      resources :uploads
      resources :money_ops
      resources :ticket_departments
      resources :tickets, :except => [:new, :edit, :update]
      post 'tickets/reply' => 'tickets#create_reply'
      get "close_ticket" => "tickets#close_ticket"
      get "report_ticket" => "tickets#report_ticket"
      post "evaluate_ticket" => "tickets#evaluate_ticket"
      resources :payers_blogs
      get "users_blogs" => "payers_blogs#users_blogs"
      get "catblogs" => "payers_blogs#catblogs"
      get "display_blog" => "payers_blogs#display_blog"
      get "blogs_sitemap.xml" => "payers_blogs#sitemap", :format => "xml", :as => :sitemap
      get "payers_blogs_categories" => "payers_blogs#payers_blogs_categories"
      resources :settings
      get "mail_setting" => "settings#mail_setting"
      
    end
  end









  resources :affilate_programs, :only => [:create, :destroy]
  #resources :countries, :only => [:index, :show]
  resources :logins, :only => [:create, :destroy]
  resources :verifications, :only => [:create, :update, :destroy]
  resources :watchdogs, :only => [:create, :show, :destroy]
  resources :users, :except => [:index, :edit]
  # root "users#dashboard"
  root "users#homepage"
  get "confirmmail" => "users#confirmmail"
  get "unlockaccount" => "users#unlockaccount"
  get "two_factor" => "users#get_two_factor"
  post "two_factor" => "users#post_two_factor"
  get "resend_two_factor" => "users#resend_two_factor"
  get "dashboard" => "users#dashboard"
  get "destroy_all_sessions" => "clearance/sessions#destroy_all_sessions"
  get "destroy_one_session" => "clearance/sessions#destroy_one_session"
  
  match 'pass_to_security_settings', to: 'users#pass_to_security_settings', via: %i(get patch post)
  get "secure_my_account" => "users#secure_my_account"
  
  get "check_mail" => "users#check_mail"
  get "check_phone" => "users#check_phone"
  get "check_country_code" => "users#check_country_code"
  get "after_sign_up" => "users#after_sign_up"
  get "resend_confirmation_mail" => "users#resend_confirmation_mail"

  get "affiliate_program" => "affilate_programs#affiliate_program"
  get "affilate_records" => "affilate_programs#affilate_records"
  get "transfer_commission" => "affilate_programs#transfer_commission"
  


  



  get "homepage" => "users#homepage"
  get "activate_account" => "user_infos#activate_account"

  get "send2fasms" => "user_infos#send2fasms"
  get "send2favoice" => "user_infos#send2favoice"
  get "resendsms" => "user_infos#resendsms"
  get "verifysms_code" => "user_infos#verifysms_code"

  
  
  match 'reset_expired_password', to: 'users#reset_expired_password', via: %i(get patch post)

  get "user_log" => "watchdogs#user_log"
  get "active_sessions" => "logins#active_sessions"
  get "send_confirmation_email" => "users#send_confirmation_email"
  get "generate_qr_code" => "users#generate_qr_code"
  get "change_two_factor" => "users#change_two_factor"
  get "send_confirmation_mail" => "users#send_confirmation_mail"
  get "confirm_google_code" => "users#confirm_google_code"
  # get "set_otp_code" => "users#set_otp_code"
  get "affilate-program/:through/:refered_by" => "affilate_programs#set_invitation_code"
  post "send_invitation_email" => "affilate_programs#send_invitation_email"
  get "edit_password/:id" => "users#edit_password" , :as => "edit_password" 
  get "error_page" => "logins#error_page"
  get "error" => "errors_logs#error"
  get "lock_page" => "logins#lock_page"
  post "lock_page" => "logins#check_to_unlock"
  # resources :cards
  #get "buy_card" => "cards#buy_card"
  get "user_cards" => "cards#user_cards"
  get "remittance" => "cards#remittance"
  get "payment_method" => "cards#payment_method"
  get "payment_data" => "cards#payment_data"
  post "pay_operation" => "cards#pay_operation"
  get "paypalurl" => "cards#paypalurl"
  get "upload_payment_data" => "cards#upload_payment_data"
  post "upload_payment_data" => "cards#upload_payment_data"
  get "charging_card" => "cards#charging_card"
  post "charging_card" => "cards#charging_card_post"
  get "check_dosite" => "cards#check_dosite"
  
  
  
  # resources :cards_categories
  get "display_cards_categories" => "cards_categories#display_cards_categories"
  resources :addresses, :except => [:new, :edit, :show]
  post "update_address" => "addresses#update_address"
  get "user_addresses" => "addresses#user_addresses"
  resources :user_wallets
  get "transfer_balance" => "user_wallets#transfer_balance"
  post "transfer_balance" => "user_wallets#transfer_balancepost"
  get "send_sms" => "user_wallets#send_sms"
  post "send_sms_post" => "user_wallets#send_sms_post"
  post "verifysms_post" => "user_wallets#verifysms_post"
  get "verifysms" => "user_wallets#verifysms"
  get "user_wallet_balance" => "user_wallets#user_wallet_balance"
  get "confirm_transfer" => "user_wallets#confirm_transfer"
  get "refund_transfer" => "user_wallets#refund_transfer"
  get "check_receiver" => "user_wallets#check_receiver"
  resources :notifications
  resources :notifications_settings
  get "user_notifications" => "notifications#user_notifications"
  get "search_notifications" => "notifications#search"
  get "add_defualt_notifications" => "notifications_settings#add_defualt_notifications"
  get "user_notifications_setting" => "notifications_settings#user_notifications_setting"
  resources :uploads
  resources :money_ops
  get "paypal" => "money_ops#paypal"
  post "paypal_post" => "money_ops#paypal_post"
  get "paypalret" => "money_ops#paypalconfirm"
  post "paypal_ipn" => "money_ops#paypal_ipn"

  get "perfectmoney" => "money_ops#perfectmoney"
  post "perfectmoneyerror" => "money_ops#perfectmoneyerror"
  post "perfectmoney" => "money_ops#perfectmoneypost"

  post "call_coinmoney" => "money_ops#call_coinmoney"
  

  get "coinmoney" => "money_ops#coinmoney"
  post "coinmoney" => "money_ops#coinmoney_post"
  resources :users_wallets_transfers

  get "withdraw_op" => "money_ops#withdraw_op"
  post "withdraw_op" => "money_ops#withdrawpost"
  get "new_transaction"=>"money_ops#new_transaction"
  
  resources :ticket_departments
  resources :tickets, :except => [:new, :edit, :update]
  post 'tickets/reply' => 'tickets#create_reply'
  get "bank_data" => "money_ops#bank_data"
  get "close_ticket" => "tickets#close_ticket"
  get "report_ticket" => "tickets#report_ticket"
  post "evaluate_ticket" => "tickets#evaluate_ticket"
  
  resources :withdraws
  resources :audit_logs, :only => [:create]
  resources :quick_payments
  get "fast_pay/:slug" => "quick_payments#fast_pay"
  post "fast_pay" => "quick_payments#fast_pay_post"
  get "trust_user" => "quick_payments#trust_user"
  get "link_check" => "quick_payments#link_check"
  resources :user_announcements
  resources :blogs_categories
  resources :payers_blogs
  get "users_blogs" => "payers_blogs#users_blogs"
  get "catblogs" => "payers_blogs#catblogs"
  get "display_blog" => "payers_blogs#display_blog"
  get "blogs_sitemap.xml" => "payers_blogs#sitemap", :format => "xml", :as => :sitemap
  get "search_blog" => "payers_blogs#search_blog"
  post "search_blog_post" => "payers_blogs#search_blog_post"
  

app/models/errors_log.rb
class ErrorsLog < ApplicationRecord
end

app/controllers/errors_logs_controller.rb
class ErrorsLogsController < ApplicationController
  before_action :set_errors_log, only: [:show, :edit, :update, :destroy]


  def error
    render :layout => false
  end

  # GET /errors_logs
  # GET /errors_logs.json
  def index
    @errors_logs = ErrorsLog.all
  end

  # GET /errors_logs/1
  # GET /errors_logs/1.json
  def show
  end

  # GET /errors_logs/new
  def new
    @errors_log = ErrorsLog.new
  end

  # GET /errors_logs/1/edit
  def edit
  end

  # POST /errors_logs
  # POST /errors_logs.json
  def create
    @errors_log = ErrorsLog.new(errors_log_params)

    respond_to do |format|
      if @errors_log.save
        format.html { redirect_to @errors_log, notice: 'Errors log was successfully created.' }
        format.json { render :show, status: :created, location: @errors_log }
      else
        format.html { render :new }
        format.json { render json: @errors_log.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /errors_logs/1
  # PATCH/PUT /errors_logs/1.json
  def update
    respond_to do |format|
      if @errors_log.update(errors_log_params)
        format.html { redirect_to @errors_log, notice: 'Errors log was successfully updated.' }
        format.json { render :show, status: :ok, location: @errors_log }
      else
        format.html { render :edit }
        format.json { render json: @errors_log.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /errors_logs/1
  # DELETE /errors_logs/1.json
  def destroy
    @errors_log.destroy
    respond_to do |format|
      format.html { redirect_to errors_logs_url, notice: 'Errors log was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_errors_log
      @errors_log = ErrorsLog.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def errors_log_params
      params.require(:errors_log).permit(:user_id, :user_type, :code, :message)
    end
end

app/helpers/errors_logs_helper.rb
module ErrorsLogsHelper
end

app/views/errors_logs/_form.html.erb
<%= form_with(model: errors_log, local: true) do |form| %>
  <% if errors_log.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(errors_log.errors.count, "error") %> prohibited this errors_log from being saved:</h2>

      <ul>
      <% errors_log.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.number_field :user_id %>
  </div>

  <div class="field">
    <%= form.label :user_type %>
    <%= form.number_field :user_type %>
  </div>

  <div class="field">
    <%= form.label :code %>
    <%= form.text_field :code %>
  </div>

  <div class="field">
    <%= form.label :message %>
    <%= form.text_field :message %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/errors_logs/edit.html.erb
<h1>Editing Errors Log</h1>

<%= render 'form', errors_log: @errors_log %>

<%= link_to 'Show', @errors_log %> |
<%= link_to 'Back', errors_logs_path %>

app/views/errors_logs/error.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    
    <!-- Title -->
    <title>404</title>

    <!-- Bootstrap -->
    <link href="/assets/css/bootstrap.min.css" rel="stylesheet" >

    <!-- Bootstrap rtl -->
    <link href="/assets/css/bootstrap.min.rtl.css" rel="stylesheet" >

    <!-- Animate -->
    <link rel="stylesheet" href="/assets/css/animate.css" >

    <!-- Fonts -->
    <link rel="stylesheet" href="/assets/css/fonts.css" >
    <link rel="stylesheet" href="/assets/css/font-awesome.min.css">

    <!-- Flags -->
    <link href="/assets/css/flags.css" rel="stylesheet">

    <!-- Style -->
    <link rel="stylesheet" href="/assets/style.css" >

    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

  </head>
  <body>

    <div id="container-style-3" class="all-height">
      <div class="container">
        <!-- Simple Head -->
        <div class="row">
          <div class="col-xs-12">
            <div class="center-simple-head">
              <a href="index.html"><h1 class="logo" title="Payers - بايرز"></h1></a>
            </div>
            <div class="simple-head text-left back-text">
              <a href="/dashboard"><i class="fa fa-arrow-left" aria-hidden="true"></i> <span>العودة للصفحة الرئيسية</span></a>
            </div>
          </div>
        </div>
      </div>

      <% @log = ErrorsLog.where(:id => params[:id]).first %>

      <div class="error-404 relative-box">
        <div class="container">
          <div class="row">
            <div class="col-xs-12">
              <div class="error-text text-center">
                <h2>نعتذر لك حدث خطأ ما !</h2>
                <h3><%=  "  رقم الخطأ " +  @log.code %></h3>
                <h4>جاهزون في مركز الدعم الفني لمساعدتك</h4>
                <img src="/assets/img/error-icon.svg" alt="الصفحة غير موجودة !">
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    

    



    <!-- Jquery Files -->
    <script src="/assets/js/jquery.min.js"></script>
    <script src="/assets/js/bootstrap.min.js"></script>
    <script src="/assets/js/jquery.flagstrap.min.js"></script>
    <script src="/assets/js/steps.js"></script>
    <script src='/assets/js/jquery-ui.min.js'></script>
    <script src='/assets/js/bootstrap-datepicker.min.js'></script>
    <script src='/assets/js/bootstrap-datepicker.ar.js'></script>
    <script src="/assets/js/main.js"></script>
  
  </body>
</html>

app/views/errors_logs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Errors Logs</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>User type</th>
      <th>Code</th>
      <th>Message</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @errors_logs.each do |errors_log| %>
      <tr>
        <td><%= errors_log.user_id %></td>
        <td><%= errors_log.user_type %></td>
        <td><%= errors_log.code %></td>
        <td><%= errors_log.message %></td>
        <td><%= link_to 'Show', errors_log %></td>
        <td><%= link_to 'Edit', edit_errors_log_path(errors_log) %></td>
        <td><%= link_to 'Destroy', errors_log, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Errors Log', new_errors_log_path %>

app/views/errors_logs/new.html.erb
<h1>New Errors Log</h1>

<%= render 'form', errors_log: @errors_log %>

<%= link_to 'Back', errors_logs_path %>

app/views/errors_logs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @errors_log.user_id %>
</p>

<p>
  <strong>User type:</strong>
  <%= @errors_log.user_type %>
</p>

<p>
  <strong>Code:</strong>
  <%= @errors_log.code %>
</p>

<p>
  <strong>Message:</strong>
  <%= @errors_log.message %>
</p>

<%= link_to 'Edit', edit_errors_log_path(@errors_log) %> |
<%= link_to 'Back', errors_logs_path %>