config/routes.rb
Rails.application.routes.draw do

  resources :errors_logs, :only => [:create]
  resources :settings
  resources :users_banks, :except => [:edit, :show]
  resources :banks, :only => [:create]
  resources :selfie_verifications, :only => [:create, :update]
  resources :address_verifications, :only => [:create, :update]
  resources :nationalid_verifications, :only => [:create, :update]
  resources :user_infos, :only => [:create]
  namespace :api, defaults: {format: 'json'} do
    namespace :v1 do
      resources :users_banks
      resources :watchdogs
      resources :users
      resources :countries
      resources :affilate_programs
      resources :selfie_verifications, :except => [:index, :destroy]
      resources :address_verifications, :except => [:index, :destroy]
      resources :nationalid_verifications, :except => [:index, :destroy]
      resources :translations
      post "users/create" => "users#create"
      get "homepage" => "users#homepage"
      post "confirmmail" => "users#confirmmail"
      post "resend_confirmmail" => "users#resend_confirmmail"
      get "two_factor" => "users#get_two_factor"
      post "two_factor" => "users#post_two_factor"
      get "send_confirmation_email" => "users#send_confirmation_email"
      get "generate_qr_code" => "users#generate_qr_code"
      get "confirm_google_code" => "users#confirm_google_code"
      get "user_log" => "watchdogs#user_log"
      get "active_sessions" => "logins#active_sessions"
      post 'auth_user' => 'authentication#authenticate_user'
      post "unlockaccount" => "authentication#unlockaccount"
      post "send_invitation_email" => "affilate_programs#send_invitation_email"
      post 'getEditToken' => 'authentication#getEditToken'
      # resources :cards
      #get "buy_card" => "cards#buy_card" 
      # resources :cards_categories
      get "display_cards_categories" => "cards_categories#display_cards_categories"
      resources :addresses, :except => [:new, :edit, :show]
      post "update_address" => "addresses#update_address"
      get "user_addresses" => "addresses#user_addresses"
      resources :user_wallets
      get "transfer_balance" => "user_wallets#transfer_balance"
      post "transfer_balance" => "user_wallets#transfer_balancepost"
      get "send_sms" => "user_wallets#send_sms"
      post "send_sms_post" => "user_wallets#send_sms_post"
      post "verifysms_post" => "user_wallets#verifysms_post"
      get "verifysms" => "user_wallets#verifysms" 
      get "user_wallet_balance" => "user_wallets#user_wallet_balance"
      resources :notifications
      resources :notifications_settings
      get "user_notifications" => "notifications#user_notifications"
      get "search_notifications" => "notifications#search"
      get "add_defualt_notifications" => "notifications_settings#add_defualt_notifications"
      resources :uploads
      resources :money_ops
      resources :ticket_departments
      resources :tickets, :except => [:new, :edit, :update]
      post 'tickets/reply' => 'tickets#create_reply'
      get "close_ticket" => "tickets#close_ticket"
      get "report_ticket" => "tickets#report_ticket"
      post "evaluate_ticket" => "tickets#evaluate_ticket"
      resources :payers_blogs
      get "users_blogs" => "payers_blogs#users_blogs"
      get "catblogs" => "payers_blogs#catblogs"
      get "display_blog" => "payers_blogs#display_blog"
      get "blogs_sitemap.xml" => "payers_blogs#sitemap", :format => "xml", :as => :sitemap
      get "payers_blogs_categories" => "payers_blogs#payers_blogs_categories"
      resources :settings
      get "mail_setting" => "settings#mail_setting"
      
    end
  end









  resources :affilate_programs, :only => [:create, :destroy]
  #resources :countries, :only => [:index, :show]
  resources :logins, :only => [:create, :destroy]
  resources :verifications, :only => [:create, :update, :destroy]
  resources :watchdogs, :only => [:create, :show, :destroy]
  resources :users, :except => [:index, :edit]
  # root "users#dashboard"
  root "users#homepage"
  get "confirmmail" => "users#confirmmail"
  get "unlockaccount" => "users#unlockaccount"
  get "two_factor" => "users#get_two_factor"
  post "two_factor" => "users#post_two_factor"
  get "resend_two_factor" => "users#resend_two_factor"
  get "dashboard" => "users#dashboard"
  get "destroy_all_sessions" => "clearance/sessions#destroy_all_sessions"
  get "destroy_one_session" => "clearance/sessions#destroy_one_session"
  
  match 'pass_to_security_settings', to: 'users#pass_to_security_settings', via: %i(get patch post)
  get "secure_my_account" => "users#secure_my_account"
  
  get "check_mail" => "users#check_mail"
  get "check_phone" => "users#check_phone"
  get "check_country_code" => "users#check_country_code"
  get "after_sign_up" => "users#after_sign_up"
  get "resend_confirmation_mail" => "users#resend_confirmation_mail"

  get "affiliate_program" => "affilate_programs#affiliate_program"
  get "affilate_records" => "affilate_programs#affilate_records"
  get "transfer_commission" => "affilate_programs#transfer_commission"
  


  



  get "homepage" => "users#homepage"
  get "activate_account" => "user_infos#activate_account"

  get "send2fasms" => "user_infos#send2fasms"
  get "send2favoice" => "user_infos#send2favoice"
  get "resendsms" => "user_infos#resendsms"
  get "verifysms_code" => "user_infos#verifysms_code"

  
  
  match 'reset_expired_password', to: 'users#reset_expired_password', via: %i(get patch post)

  get "user_log" => "watchdogs#user_log"
  get "active_sessions" => "logins#active_sessions"
  get "send_confirmation_email" => "users#send_confirmation_email"
  get "generate_qr_code" => "users#generate_qr_code"
  get "change_two_factor" => "users#change_two_factor"
  get "send_confirmation_mail" => "users#send_confirmation_mail"
  get "confirm_google_code" => "users#confirm_google_code"
  # get "set_otp_code" => "users#set_otp_code"
  get "affilate-program/:through/:refered_by" => "affilate_programs#set_invitation_code"
  post "send_invitation_email" => "affilate_programs#send_invitation_email"
  get "edit_password/:id" => "users#edit_password" , :as => "edit_password" 
  get "error_page" => "logins#error_page"
  get "error" => "errors_logs#error"
  get "lock_page" => "logins#lock_page"
  post "lock_page" => "logins#check_to_unlock"
  # resources :cards
  #get "buy_card" => "cards#buy_card"
  get "user_cards" => "cards#user_cards"
  get "remittance" => "cards#remittance"
  get "payment_method" => "cards#payment_method"
  get "payment_data" => "cards#payment_data"
  post "pay_operation" => "cards#pay_operation"
  get "paypalurl" => "cards#paypalurl"
  get "upload_payment_data" => "cards#upload_payment_data"
  post "upload_payment_data" => "cards#upload_payment_data"
  get "charging_card" => "cards#charging_card"
  post "charging_card" => "cards#charging_card_post"
  get "check_dosite" => "cards#check_dosite"
  
  
  
  # resources :cards_categories
  get "display_cards_categories" => "cards_categories#display_cards_categories"
  resources :addresses, :except => [:new, :edit, :show]
  post "update_address" => "addresses#update_address"
  get "user_addresses" => "addresses#user_addresses"
  resources :user_wallets
  get "transfer_balance" => "user_wallets#transfer_balance"
  post "transfer_balance" => "user_wallets#transfer_balancepost"
  get "send_sms" => "user_wallets#send_sms"
  post "send_sms_post" => "user_wallets#send_sms_post"
  post "verifysms_post" => "user_wallets#verifysms_post"
  get "verifysms" => "user_wallets#verifysms"
  get "user_wallet_balance" => "user_wallets#user_wallet_balance"
  get "confirm_transfer" => "user_wallets#confirm_transfer"
  get "refund_transfer" => "user_wallets#refund_transfer"
  get "check_receiver" => "user_wallets#check_receiver"
  resources :notifications
  resources :notifications_settings
  get "user_notifications" => "notifications#user_notifications"
  get "search_notifications" => "notifications#search"
  get "add_defualt_notifications" => "notifications_settings#add_defualt_notifications"
  get "user_notifications_setting" => "notifications_settings#user_notifications_setting"
  resources :uploads
  resources :money_ops
  get "paypal" => "money_ops#paypal"
  post "paypal_post" => "money_ops#paypal_post"
  get "paypalret" => "money_ops#paypalconfirm"
  post "paypal_ipn" => "money_ops#paypal_ipn"

  get "perfectmoney" => "money_ops#perfectmoney"
  post "perfectmoneyerror" => "money_ops#perfectmoneyerror"
  post "perfectmoney" => "money_ops#perfectmoneypost"

  post "call_coinmoney" => "money_ops#call_coinmoney"
  

  get "coinmoney" => "money_ops#coinmoney"
  post "coinmoney" => "money_ops#coinmoney_post"
  resources :users_wallets_transfers

  get "withdraw_op" => "money_ops#withdraw_op"
  post "withdraw_op" => "money_ops#withdrawpost"
  get "new_transaction"=>"money_ops#new_transaction"
  
  resources :ticket_departments
  resources :tickets, :except => [:new, :edit, :update]
  post 'tickets/reply' => 'tickets#create_reply'
  get "bank_data" => "money_ops#bank_data"
  get "close_ticket" => "tickets#close_ticket"
  get "report_ticket" => "tickets#report_ticket"
  post "evaluate_ticket" => "tickets#evaluate_ticket"
  
  resources :withdraws
  resources :audit_logs, :only => [:create]
  resources :quick_payments
  get "fast_pay/:slug" => "quick_payments#fast_pay"
  post "fast_pay" => "quick_payments#fast_pay_post"
  get "trust_user" => "quick_payments#trust_user"
  get "link_check" => "quick_payments#link_check"
  resources :user_announcements
  resources :blogs_categories
  resources :payers_blogs
  get "users_blogs" => "payers_blogs#users_blogs"
  get "catblogs" => "payers_blogs#catblogs"
  get "display_blog" => "payers_blogs#display_blog"
  get "blogs_sitemap.xml" => "payers_blogs#sitemap", :format => "xml", :as => :sitemap
  get "search_blog" => "payers_blogs#search_blog"
  post "search_blog_post" => "payers_blogs#search_blog_post"
  

app/models/card.rb
class Card < ApplicationRecord
    has_one_attached :payment_receipt
    validates_uniqueness_of :number
    # validate :check_value
    # validate :check_expiration
    before_save :default_values
    # validates :value, numericality: { only_integer: true }
    validates :status, numericality: { only_integer: true }
    validates :user_id, numericality: { only_integer: true , greater_than: 0 }
    has_many :cards_log , foreign_key: "card_id"

    def default_values
        self.number ||= [*('0'..'9'),*('a'..'z')].to_a.shuffle[0,16].join
    end

    def self.checkdeposit(current_user,amount,bank_type,bank_key)
        @user = current_user
        @value = amount.to_f
        @bank_type = bank_type
        @bank_key = bank_key
        @user_group = UsersGroup.where(id: @user.users_group_id).first
        @group_bank_limits = GroupsBanksLimit.where(bank_type: @bank_type, group_id: @user.users_group_id).first
        @company_bank = CompanyBank.where(bank_key: @bank_key).first
        @user_account_status = UserInfo.where(user_id: @user.id).first

        @message = ""

        if @value < @user_group.minimum_deposite_per_time.to_f
            @message  = @message + I18n.t("cards.deposit_greater_than") + "#{@user_group.minimum_deposite_per_time}" + " "  + I18n.t("users.USD")
        end

        if (@user.daily_deposite_number.to_i) >= (@user_group.daily_deposite_number.to_i)
            @message  = @message + I18n.t("cards.exceeded_daily_deposit_requests")
        end

        if (@user.total_daily_deposite.to_f + @value) > (@group_bank_limits.maximum_daily_deposite.to_f)
            @message  = @message + I18n.t("cards.exceeded_daily_deposit_amount")
        end

        if (@user.total_monthly_deposite.to_f + @value) > (@group_bank_limits.maximum_monthly_deposite.to_f)
            @message  = @message + I18n.t("cards.exceeded_monthly_deposit_amount")
        end

        if !(@user_account_status) or (@user_account_status.status == "UnVerified")
          if (@company_bank.unverified_deposite == false)
            @message  = @message + I18n.t("cards.bank_disabled_for_unverified_users")
          end
        elsif (@company_bank.verified_deposite == false)
          @message  = @message + I18n.t("cards.bank_is_disabled_by_admin")         
        end

        if @user.allowed_bank_level < @company_bank.severity_level
          @message  = @message + I18n.t("cards.this_bank_is_blocked_for_you") 
        end

        return   @message 



    end

    def self.payers_deposit_expenses(users_group,value)
      @users_group = users_group.to_i
      @value = value.to_f
      @deposite_expenses = UsersGroup.where(:id => @users_group.to_i).first
      @expenses = @value * (@deposite_expenses.deposite_ratio/100) + @deposite_expenses.deposite_fees
      return   @expenses 

    end

    # def check_value
    #   errors.add(:value, "must be equal or greater than 5 USD") if value == nil || value < 5
    # end

    # def check_expiration
    #     errors.add(:expired_at, "Must be at least two days from now") if expired_at < Date.today + 2.days
    # end

end

app/helpers/cards_helper.rb
module CardsHelper
end

app/views/cards/_form.html.erb
<%= form_with(model: card, local: true) do |form| %>
  <% if card.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(card.errors.count, "error") %> prohibited this card from being saved:</h2>

      <ul>
      <% card.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :value %>
    <%= form.number_field :value %>
  </div>

  <div class="field">
    <%= form.label :status %>
    <%= form.select :status,options_for_select([['Active',1],['Charged',2],['pending',3],['disabled',4]]),  {}, {} %>
  </div>

  <div class="field">
    <%= form.label :expired_at %>
    <%= form.date_select :expired_at %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.number_field :user_id %>
  </div>

  <div class="field">
    <%= form.label :invoice_id %>
    <%= form.number_field :invoice_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/cards/charging_card.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    
    <!-- Title -->
    <title>كارت بايرز</title>

    <% if I18n.locale.to_s == "en" %>

      <!-- Bootstrap -->
      <link href="/assets/en/css/bootstrap.min.css" rel="stylesheet" >

      <!-- Animate -->
      <link rel="stylesheet" href="/assets/en/css/animate.css" >

      <!-- Fonts -->
      <link rel="stylesheet" href="/assets/en/css/fonts.css" >
      <link rel="stylesheet" href="/assets/en/css/font-awesome.min.css">

      <!-- Flags -->
      <link href="/assets/en/css/flags.css" rel="stylesheet">

      <!-- Style -->
      <link rel="stylesheet" href="/assets/en/style.css" >

    <% else %>

      <!-- Bootstrap -->
      <link href="/assets/css/bootstrap.min.css" rel="stylesheet" >

      <!-- Bootstrap rtl -->
      <link href="/assets/css/bootstrap.min.rtl.css" rel="stylesheet" >

      <!-- Animate -->
      <link rel="stylesheet" href="/assets/css/animate.css" >

      <!-- Fonts -->
      <link rel="stylesheet" href="/assets/css/fonts.css" >
      <link rel="stylesheet" href="/assets/css/font-awesome.min.css">

      <!-- Flags -->
      <link href="/assets/css/flags.css" rel="stylesheet">

      <!-- Style -->
      <link rel="stylesheet" href="/assets/style.css" >

    <% end %>

    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

  </head>
  <body>

    <!-- Deposite By Payers Card -->
    <div class="container all-height">
      <div class="row">
        <div class="col-lg-12">
          <div class="simple-head-2 simple-head-card">
            <a href="/remittance" class="back-to"><i class="back-arrow"></i></a>
            <div class="center-simple-head">
              <h1><%= t('cards.new_deposit_operation')%></h1>
              <span><%= t('cards.secure_data')%></span>
            </div>
            <a href="/dashboard"><button class="button-4"><%= t('cards.back_to_main')%></button></a>
          </div>
        </div>
        <% flash.each do |key, value| -%>
          <div class="col-lg-12">
                <div id="flash_<%= key %>"><%=h value %></div>
          </div>
        <% end %>
      </div>

      <div class="row">
        <div class="col-xs-12">
          <div class="payers-card">
            <div class="payers-card-row margin-b-30 margin-t-30">
              <img class="payers-card-text" src="/assets/img/payers-card-text.svg"  alt="Payers - بايرز">
              <img class="payers-card-logo" src="/assets/img/payers-card-logo.svg"  alt="Payers - بايرز">
            </div>
            <%= form_for :charging_card ,:url => charging_card_path,:html => { :multipart => true } do |f| %>
            <div class="inputstyle inputarial margin-b-25">
              <input type="text" maxlength="19" id="charging_card" name="charging_card[card_number]" placeholder="XXXX   -   XXXX   -   XXXX   -   XXXX">
            </div>
            <div class="payers-card-row">
              <button type="submit" class="button-2"><%= t('cards.deposit_card')%></button>
              <p><%= t('cards.cannot_refund_card')%> <span>Payers.net</span></p>
            </div>
            <% end %>
          </div>
        </div>
        <div class="col-xs-12 text-center margin-t-40">
          <div class="payers-card-foot">
            <a href="#"><%= t('cards.what_is_payers_cards')%></a>
            <a href="#"><%= t('cards.where_to_find_payers_cards')%></a>
          </div>
        </div>
      </div>
    </div>
    <!-- Deposite By Payers Card -->
  
  </body>
</html>

<%= render :partial => 'layouts/script' %>

<script>
$("#charging_card").keyup(function() {
    var foo = $(this).val().replace(/-/g, ""); // remove hyphens
    // You may want to remove all non-digits here
    // var foo = $(this).val().replace(/\D/g, "");
    
    if (foo.length > 0) {
    
        var output = "";
        var idx = 0;
        for (var i = 0; i < [4, 4, 4, 4].length && idx < foo.length; i++) {
                output += foo.substr(idx, [4, 4, 4, 4][i]);
                if (idx + [4, 4, 4, 4][i] < foo.length) output += "-";
                idx += [4, 4, 4, 4][i];
        }     
        output += foo.substr(idx);   
    } 
    $("#charging_card").val(output);
});
</script>

app/views/cards/new.html.erb
<h1>New Card</h1>

<%= render 'form', card: @card %>

<%= link_to 'Back', cards_path %>

app/views/cards/remittance.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    
    <!-- Title -->
    <title>معاملة إيداع جديدة</title>

    <% if I18n.locale.to_s == "en" %>

      <!-- Bootstrap -->
      <link href="/assets/en/css/bootstrap.min.css" rel="stylesheet" >

      <!-- Animate -->
      <link rel="stylesheet" href="/assets/en/css/animate.css" >

      <!-- Fonts -->
      <link rel="stylesheet" href="/assets/en/css/fonts.css" >
      <link rel="stylesheet" href="/assets/en/css/font-awesome.min.css">

      <!-- Flags -->
      <link href="/assets/en/css/flags.css" rel="stylesheet">

      <!-- Style -->
      <link rel="stylesheet" href="/assets/en/style.css" >

    <% else %>

      <!-- Bootstrap -->
      <link href="/assets/css/bootstrap.min.css" rel="stylesheet" >

      <!-- Bootstrap rtl -->
      <link href="/assets/css/bootstrap.min.rtl.css" rel="stylesheet" >

      <!-- Animate -->
      <link rel="stylesheet" href="/assets/css/animate.css" >

      <!-- Fonts -->
      <link rel="stylesheet" href="/assets/css/fonts.css" >
      <link rel="stylesheet" href="/assets/css/font-awesome.min.css">

      <!-- Flags -->
      <link href="/assets/css/flags.css" rel="stylesheet">

      <!-- Style -->
      <link rel="stylesheet" href="/assets/style.css" >

    <% end %>

    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

  </head>
  <body>

<% if @deposit_status.where(key: "deposit_status").pluck(:value).first == "on" %>
<br>
<span style="color: red;font-size: x-large;border:1px solid red;margin-left: 450px;"><%= @deposit_status.where(key: "deposit_msg").pluck(:value).first %></span>
<% else %>

    <div class="white-page all-height">
      <!-- Deposite Steps -->
      <div class="container">
        <!-- Header -->
        <div class="row">
          <div class="col-lg-12">
            <div class="simple-head-3 simple-head-4 relative-box">
              <a href="/new_transaction" class="back-to"><i class="back-arrow"></i></a>
              <div class="center-simple-head">
                <h1><%= t('cards.what_deposit_method')%></h1>
              </div>
              <a href="/dashboard" class="close-button"><i class="fa fa-times" aria-hidden="true"></i></a>
            </div>
          </div>
        </div>
        <!-- Header -->

        <!-- Deposite Transaction -->
        <div class="row">
          <div class="col-md-8 col-md-offset-2">
            <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12 text-center">
              <div class="deposite-transaction-card">
                <div class="deposite-transaction-img">
                  <img src="/assets/img/payers-card.svg" alt="payers-card">
                </div>
                <h2><%= t('cards.payers_cards')%></h2>
                <p class="paragraph-2"><%= t('cards.payers_cards_artical')%></p>
                <a href="/charging_card" class="button-3"><%= t('cards.payers_prepaid_cards')%></a>
              </div>
            </div>
            <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12 text-center">
              <div class="deposite-transaction-card">
                <div class="deposite-transaction-img">
                  <img src="/assets/img/credit-card.svg" alt="credit-card">
                </div>
                <h2><%= t('cards.credit_card_or_banks')%></h2>
                <p><%= t('cards.credit_card_or_banks_artical')%></p>
                <a href="/payment_method" class="button-3"><%= t('cards.credits_or_banks')%></a>
              </div>
            </div>
          </div>
        </div>
        <!-- Deposite Transaction -->
      </div>
    </div>
<% end %>
  </body>
</html>
<!-- Jquery Files -->
<script src="/assets/js/jquery.min.js"></script>
<script src="/assets/js/bootstrap.min.js"></script>
<script src="/assets/js/jquery.flagstrap.min.js"></script>
<script  src="/assets/js/steps.js"></script>
<script src='/assets/js/jquery-ui.min.js'></script>
<script src='/assets/js/bootstrap-datepicker.min.js'></script>
<script src='/assets/js/bootstrap-datepicker.ar.js'></script>
<script src="/assets/js/main.js"></script>

app/views/cards/user_cards.html.erb
<h1>User Cards</h1>

<table>
  <thead>
    <tr>
      <th>Number</th>
      <th>Value</th>
      <th>Net Value</th>
      <th>Status</th>
      <th>Expired at</th>
      <th>Operation ID</th>
      <th>User Account Number</th>
      <th>Invoice</th>
      <th>User Note</th>
    </tr>
  </thead>

  <tbody>
    <% @user_cards.each do |card| %>
      <tr>
        <% if card.status == 3 %>
        <td><%= "****-****-****-****" %></td>
        <% else %>
        <td><%= card.number.scan(/.{1,4}/).join('-') %></td>
        <% end %>
        <td><%= card.value %></td>
         <td><%= card.net_value %></td>
        <% if card.status == 1 %>
        <td><%= "Active" %></td>
        <% elsif card.status == 2 %>
        <td><%= "Charged" %></td>
        <% elsif card.status == 3 %>
            <td><%= "pending" %></td>
        <% elsif card.status == 4 %>
            <td><%= "disabled" %></td>
        <% end %>
        <td><%= card.expired_at %></td>
        <td><%= card.operation_id %></td>
        <td><%= card.user_account_number %></td>
        <td><%= card.invoice_id %></td>
        <td><%= card.note %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<button><%= link_to 'Buy New Card', display_cards_categories_path %></button>